kind: pipeline
type: docker
name: imgproxy


steps:
  - name: lint
    image: golangci/golangci-lint:v1.21.0
    commands: 
      - golangci-lint run .

  - name: test
    image: golang:1.13
    commands: 
      - go test -v