kind: pipeline
type: docker
name: imgproxy


steps:
  - name: lint
    image: golangci/golangci-lint:v1.21.0
    commands: 
      - golangci-lint run .

  - name: test
    image: golang:1.13
    commands: 
      - echo 'LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/root/vips/<< 8.8 >>/lib"' >> $BASH_ENV
      - echo 'PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/root/vips/<< 8.8 >>/lib/pkgconfig"' >> $BASH_ENV
      - go test -v